#
# Makefile for the video capture/playback device drivers.
#
obj-y				+= avp/
obj-$(CONFIG_TEGRA_CAMERA)	+= tegra_camera.o
obj-$(CONFIG_VIDEO_OV5650)	+= ov5650.o
obj-$(CONFIG_VIDEO_OV2710)	+= ov2710.o
obj-$(CONFIG_VIDEO_YUV)	        += yuv_sensor.o
obj-$(CONFIG_VIDEO_YUV5)	+= yuv5_sensor.o
obj-$(CONFIG_VIDEO_AD5820)	+= ad5820.o
obj-$(CONFIG_VIDEO_LTC3216)	+= ltc3216.o
